version: 0.2

env:
  variables:
    ECR_REPOSITORY_URI: "767842236881.dkr.ecr.us-east-1.amazonaws.com/ecr"
phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $ECR_REPOSITORY_URI
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - echo ls
      - docker build -t coworking-analytics /analytics
      - echo Tagging the Docker image...
      - docker tag coworking-analytics:latest $ECR_REPOSITORY_URI:latest
      - docker tag coworking-analytics:latest $ECR_REPOSITORY_URI:$CODEBUILD_BUILD_NUMBER
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker images...
      - docker push $ECR_REPOSITORY_URI:latest
      - docker push $ECR_REPOSITORY_URI:$CODEBUILD_BUILD_NUMBER
artifacts:
  files: '**/*'
