apiVersion: v1
kind: Service
metadata:
  name: coworking
spec:
  type: LoadBalancer
  selector:
    service: coworking
  ports:
  - name: "5153"
    protocol: TCP
    port: 5153
    targetPort: 5153
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: coworking
  labels:
    name: coworking
spec:
  replicas: 1
  selector:
    matchLabels:
      service: coworking
  template:
    metadata:
      labels:
        service: coworking
    spec:
      containers:
      - name: coworking
        image: "767842236881.dkr.ecr.us-east-1.amazonaws.com/ecr:latest"  # Replace with your actual Docker image URI
        imagePullPolicy: IfNotPresent
        livenessProbe:
          httpGet:
            path: /health_check
            port: 5153
          initialDelaySeconds: 5
          timeoutSeconds: 2
        readinessProbe:
          httpGet:
            path: "/readiness_check"
            port: 5153
          initialDelaySeconds: 5
          timeoutSeconds: 5
        envFrom:
        - configMapRef:
            name: coworking-config  # Replace with your actual ConfigMap name
        env:
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: coworking-config  # Replace with your actual ConfigMap name
              key: DB_HOST
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: coworking-config  # Replace with your actual ConfigMap name
              key: DB_NAME
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              name: coworking-config  # Replace with your actual ConfigMap name
              key: DB_PORT
        - name: DB_USERNAME
          valueFrom:
            configMapKeyRef:
              name: coworking-config  # Replace with your actual Secret name
              key: DB_USERNAME  # Replace with the actual key from your Secret
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: coworking-secret  # Replace with your actual Secret name
              key: DB_PASSWORD  # Replace with the actual key from your Secret
      restartPolicy: Always
